### ISSUE TITLE
Crash when 2 or more bridges in same network

### ISSUE THREAD

**Issue by olikdesign** [joao7yt/CSHUE#3]
Hello,

i have an error occuring while starting the programm. 
I tested it at an other machine and there it worked, how it was expected.

Any ideas?

It says the following:

```
HResult:    -2146233079
HelpLink:   
Message:    The calling thread must be STA, because many UI components require this.
Source:     PresentationCore
```

**Comment by joao7yt** [comment]
Can you attach the log file(s) created in the log folder?

**Comment by olikdesign** [comment]
Version:    2019.290.174.26
HResult:    -2146233079
HelpLink:   
Message:    The calling thread must be STA, because many UI components require this.
Source:     PresentationCore
StackTrace: at System.Windows.Input.InputManager..ctor()
            at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
            at System.Windows.Input.KeyboardNavigation..ctor()
            at System.Windows.FrameworkElement.FrameworkServices..ctor()
            at System.Windows.FrameworkElement.EnsureFrameworkServices()
            at System.Windows.FrameworkElement..ctor()
            at System.Windows.Controls.Control..ctor()
            at System.Windows.Window..ctor()
            at CSHUE.Views.HubSelector..ctor(List`1 list) in D:\Users\John\Documents\Projects\CSHUE\CSHUE\Views\HubSelector.xaml.cs:line 22
            at CSHUE.ViewModels.MainWindowViewModel.<GetBridgeIpAsync>d__56.MoveNext() in D:\Users\John\Documents\Projects\CSHUE\CSHUE\ViewModels\MainWindowViewModel.cs:line 780
--- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at CSHUE.ViewModels.MainWindowViewModel.<HueAsync>d__55.MoveNext() in D:\Users\John\Documents\Projects\CSHUE\CSHUE\ViewModels\MainWindowViewModel.cs:line 694
--- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
            at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
            at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
            at System.Windows.Threading.DispatcherOperation.InvokeImpl()
            at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
            at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
            at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
            at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
            at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
            at System.Windows.Threading.DispatcherOperation.Invoke()
            at System.Windows.Threading.Dispatcher.ProcessQueue()
            at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
            at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
            at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
            at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
            at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
            at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
            at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
            at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
            at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
            at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
            at System.Windows.Application.RunDispatcher(Object ignore)
            at System.Windows.Application.RunInternal(Window window)
            at System.Windows.Application.Run(Window window)
            at CSHUE.App.Main() in D:\Users\John\Documents\Projects\CSHUE\CSHUE\App.xaml.cs:line 304

**Comment by joao7yt** [comment]
Do you have more than one hub?

**Comment by olikdesign** [comment]
Yes 2 Hubs

**Comment by joao7yt** [comment]
I’m almost sure it has something to do with it... As I don’t have two hubs, I couldn’t test the hub selector feature that I implemented... But as soon as I can get to my computer I will solve this.

For now, you can try to turn off the hub you are not going to use and see if the application starts fine.

If you’re going to try it, do this way: unplug your hub (or just its ethernet cable), restart both your modem and your computer.

**Comment by olikdesign** [comment]
I will try it. I really like your program. I dont know why its not popular.

**Comment by joao7yt** [comment]
Oh, thank you! :) How did you get to know about CSHUE?

**Comment by olikdesign** [comment]
I love the use of Philips Hue bulbs and playing CS since 15 years. So i just looking for a option to connect these. On Youtube i found your Video, so i came here.

I think if you would promote yourself it would go viral.

**Comment by joao7yt** [comment]
I tried... i posted on GlobalOffensive and Hue subreddits but didn’t get much attention... Maybe I will post again when I polish the app some more...

Do you speak only English?

**Comment by olikdesign** [comment]
I come from germany. So english is only my second language.

**Comment by joao7yt** [comment]
If you have time and interest, it would be cool to have the app translated to german... I already have a guy doing the french translation btw... :)

**Comment by olikdesign** [comment]
Yes sure. I really would enjoy this.

**Comment by joao7yt** [comment]
Do you have discord?

**Comment by olikdesign** [comment]
Teamspeak

**Comment by joao7yt** [comment]
Do you have some social network where we could chat in private then? Like WhatsApp, facebook...

**Comment by olikdesign** [comment]
Yes write me your number so we can chat on WhatsApp.

**Comment by joao7yt** [comment]
+55 19998467071

**Comment by olikdesign** [comment]
i texted you.
